#FROM node:14-alpine AS development
FROM node:19.9.0-slim
WORKDIR /app
COPY ./app /app

RUN apt update && apt upgrade -y

RUN npm install
RUN npm run build --production
RUN npm install -g serve

#CMD npm run start -- -p 80
#CMD ["npm", "start", "--port 80"]
CMD serve -s build -l 80