version: '3.8'

services:
 lez-front:
    container_name: lez-front
    image: app-dev
    build:
      context: ./
    volumes:
      - ./app:/app
    expose:
      - 80  
    networks:
      - internal
      - web


networks:
   web:
     external: true
   internal:
     external: false

